const PageStateActionTypes = {
  UPDATE_PAGE_STATE: 'UPDATE_PAGE_STATE',
  FETCH_COLLECTIONS_START: 'FETCH_COLLECTIONS_START',
  FETCH_COLLECTIONS_SUCCESS: 'FETCH_COLLECTIONS_SUCCESS',
  FETCH_COLLECTIONS_FAILURE: 'FETCH_COLLECTIONS_FAILURE',
};

export default PageStateActionTypes;
